name = "JuliaNotes"
uuid = "bb23d089-5b45-4deb-921c-94082d129500"
authors = ["Leandro Martinez <leandro@iqm.unicamp.br> and contributors"]
version = "0.3.10"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
